C     Declaration des differentes couleurs
C -
      INTEGER  COLCO , COLAD , COLAX , COLER
      INTEGER  COLFCT, COLNOM, CCADR, CCOM, CFOND
C -
C - COULEUR DE TRAIT MAILLAGE INITIAL
      INTEGER  CTRAIT
C - COULEUR DES NUMEROS DE NOEUDS
      INTEGER  CNUMNE
C - COULEUR DES NUMEROS D"ELEMENTS
      INTEGER  CNUMEL
C - COULEUR DE TRAIT MAILLAGE DEFORME
      INTEGER  CDEPL
C -
C- ROUGE
      PARAMETER (COLCO = 48)
C VERT      
      PARAMETER (COLAD = 64)
C NOIR      
      PARAMETER (COLAX = 1)
      PARAMETER (COLER = 1)
      PARAMETER (COLFCT = 1)
      PARAMETER (COLNOM = 1)
      PARAMETER (CCADR = 1)
      PARAMETER (CCOM = 1)
C BLANC      
      PARAMETER (CFOND = 2)
      PARAMETER (CTRAIT = 1)
      PARAMETER (CNUMNE = 64)
      PARAMETER (CNUMEL = 48)
C ROUGE      
      PARAMETER (CDEPL = 16)
