      INTEGER MELEMD,MPOIND,MSEGME,MSEUIL,MLOGSE
C
C * nombre maximal d'elements *
      PARAMETER (MELEMD=20000)
C
C * nombre maximal de noeuds *
      PARAMETER (MPOIND=15000)
C
C * nombre maximal de segments tracables *
      PARAMETER (MSEGME=MELEMD+MPOIND)
      PARAMETER (MLOGSE=100*MSEGME)
C
C * Nombre maximal de seuils pour trace de champ *
      PARAMETER (MSEUIL=13)
C
C * table de connexion de chaque element *
      INTEGER NELEM,LBANDE
      INTEGER LNODS(MELEMD,9)
C
C * type d element (triangle a 3 noeuds .... quadrilatere a 9 noeuds) *
C * sans oublier les barres et les coques axisymetriques *
      INTEGER NNEU(MELEMD)
      CHARACTER*4 TYPEL(MELEMD)
C
C * coordonnees de chaque noeud *
      INTEGER NPOIN,PRENEU,DERNEU
      REAL*4 COORD(MPOIND,3)
C
C * deplacements de chaque noeud *
      REAL*4 DEPLAC(MPOIND,3),AMPLIX,AMPLIY,AMPLIZ
C
C * auxiliaires de tracage *
      INTEGER NSEGME
      LOGICAL*1 LOGSEG(MLOGSE)
      LOGICAL*1 DEJSEG
      INTEGER*4 INFSEG(MSEGME,2)
      REAL*4 XSEGDE(MSEGME),YSEGDE(MSEGME)
      REAL*4 XSEGAR(MSEGME),YSEGAR(MSEGME)
      REAL*4 XELEM(9),YELEM(9)
C
C * coordonnees (x,y) du centre de gravite de chaque element *
      REAL*4 GRAVEL(MELEMD,2)
C
C * taille de chaque element *
      REAL*4 TAILEL(MELEMD)
C
C
      CHARACTER*40 BLAN40
      CHARACTER*50 BLAN50,FICHIE
      CHARACTER*80 BLAN80
      CHARACTER*1 BLAN1
      CHARACTER*1 REP,CREP,CLETTR
      CHARACTER*3 REV
      CHARACTER*3 INV
      CHARACTER*50 FIMAIL,FIDEPL,FICHAM
      INTEGER      LFIMAI,LFIDEP,LFICHA 
      INTEGER UNMAIL,UNDEPL,UNCHAM,UNBENS,UNCLAV,UNECRA
      LOGICAL OPMAIL,OPDEPL,OPCHAM,OPBENS
      LOGICAL MAILLU,DEPLLU,CHAMLU,DEJLU
C
      INTEGER OPTION,OLDOPT
C
C * Variables de seuil pour champ *
      INTEGER NSEUIL
      REAL*4 SEUIL(MSEUIL),SEUILD(MSEUIL),SEUMIN,SEUMAX,SEUMID,SEUMAD
      REAL*4 CHAMP(MELEMD)
C
C * Variables de couleur *
      INTEGER CSEUIL(MSEUIL),CSEUID(MSEUIL)
      INTEGER CELEM(MELEMD)
C
C * Caractere de pointe *
      LOGICAL POINTE(MELEMD)
      INTEGER NUMPOI(MSEUIL),NUMPOD(MSEUIL)
C
C * Numerotation .elem. ou non,depl. ou non,champ ou non,elem. dissocie ou non *
      LOGICAL NUMNEU, NUMELE, LOMAIL, LODEPL, LOCHAM, LODISS, LOZOOM
      LOGICAL LODISN
C
C * Coloration linearisee des champ ou non *
      LOGICAL LOCHLI
C
C * Maillage bidim ou tridim *
      LOGICAL LOBIDI,LOTRID
      REAL POINVU(3),PROJEC(3,3)
C
C * pour interpreteur *
C
      INTEGER          LECINT , LGCARG
      DOUBLE PRECISION LECDBL
      LOGICAL          LECLOG
C 
C 
C * Definition des domaines et fenetres de trace *
      REAL*4 XORB,YORB,XLB,YLB,XMINB,YMINB,XMAXB,YMAXB
      REAL*4 XLBOLD,YLBOLD,ECHCAX,ECHCAY
      REAL*4 XORE,YORE,XLE,YLE,XMINE,YMINE,XMAXE,YMAXE
      REAL*4 XORS,YORS,XLS,YLS,XMINS,YMINS,XMAXS,YMAXS
      REAL*4 XORC,YORC,XLC,YLC,XMINC,YMINC,XMAXC,YMAXC
      REAL*4 XORM,YORM,XLM,YLM,XMINM,YMINM,XMAXM,YMAXM
      REAL*4 XOROM,YOROM,XLOM,YLOM,XMINOM,YMINOM,XMAXOM,YMAXOM
      REAL*4 XORSM,YORSM,XLSM,YLSM,XMINSM,YMINSM,XMAXSM,YMAXSM
      REAL*4 ECHOS
C
      COMMON/ELEM/NELEM,LNODS,NNEU,LBANDE,GRAVEL,TAILEL,CHAMP
      COMMON/CELEM/TYPEL
      COMMON/NOEUD/NPOIN,COORD,PRENEU,DERNEU
      COMMON/DEPLA/DEPLAC,AMPLIX,AMPLIY,AMPLIZ
      COMMON/TRIDIM/POINVU,PROJEC
      COMMON/SEGMEN/NSEGME,LOGSEG,INFSEG,XSEGDE,YSEGDE,XSEGAR,YSEGAR,
     &              XELEM,YELEM,DEJSEG
      COMMON/FILES/UNMAIL,UNDEPL,UNCHAM,UNBENS,OPMAIL,OPDEPL,OPCHAM,
     &             OPBENS,UNCLAV,UNECRA
      COMMON/CFILES/FIMAIL,FIDEPL,FICHAM
      COMMON/LFILES/LFIMAI,LFIDEP,LFICHA
      COMMON/CBIDON/REP,CREP,CLETTR,BLAN50,BLAN80,BLAN1,BLAN40
      COMMON/GESTER/REV,INV
      COMMON/GESOPT/OPTION,OLDOPT,NUMNEU,NUMELE,LOMAIL,LODEPL,LOCHAM,
     &              LOCHLI,LODISS,LOZOOM,LODISN,LOBIDI,LOTRID
      COMMON/GESFIL/MAILLU,DEPLLU,CHAMLU,DEJLU
      COMMON/GESPOI/POINTE,NUMPOI,NUMPOD
      COMMON/GESCOU/CELEM,CSEUIL,CSEUID
      COMMON/GESSEU/NSEUIL,SEUIL,SEUILD,SEUMIN,SEUMAX,SEUMID,SEUMAD
      COMMON/GESFEN/XORB,YORB,XLB,YLB,XMINB,YMINB,XMAXB,YMAXB,
     &              XLBOLD,YLBOLD,ECHCAX,ECHCAY,
     &              XORE,YORE,XLE,YLE,XMINE,YMINE,XMAXE,YMAXE,
     &              XORS,YORS,XLS,YLS,XMINS,YMINS,XMAXS,YMAXS,
     &              XORC,YORC,XLC,YLC,XMINC,YMINC,XMAXC,YMAXC,
     &              XORM,YORM,XLM,YLM,XMINM,YMINM,XMAXM,YMAXM,
     &              XOROM,YOROM,XLOM,YLOM,XMINOM,YMINOM,XMAXOM,YMAXOM,
     &              XORSM,YORSM,XLSM,YLSM,XMINSM,YMINSM,XMAXSM,YMAXSM,
     &              ECHOS
